# theme: owner/name --> Don't forget to remove/comment the gem-based theme option
remote_theme: "johno/pixyll"

# Site settings
title: Aby's dots
email: your_email@example.com
author: Aby
description: "simple, beautiful dots for aesthetic workflow."
baseurl: ""
url: "https://sharkaby.com/"

# Build settings
markdown: kramdown
permalink: pretty
paginate: 3
